### ISSUE TITLE
Avoiding the use of dummy email in the unit tests

### ISSUE THREAD

**Issue by paavininanda** [systers/PC-Prep-Kit#107]
## Description
As a programmer,
I need the unit tests to work properly,
so that I can have the app function without any glitches.
Currently one of the test related to authentication is failing -

> Executing (default): SELECT `id`, `fname`, `lname`, `email`, `password`, `verificationStatus`, `resetPasswordToken`, `resetPasswordExpires`, `provider`, `google_id`, `google_token` FROM `user_accounts` AS `user_account` WHERE `user_account`.`email` = 'pcpreptest@send22u.info' LIMIT 1;
POST /auth/login 200 6.072 ms - 61
        1) "before all" hook: Login
Executing (default): DELETE FROM `user_accounts` WHERE `email` = 'pcpreptest@send22u.info'
  3 passing (275ms)
  1 failing
>  1) Testing APIs Creating User Authentication "before all" hook: Login:
     Uncaught TypeError: Cannot read property 'email' of undefined
      at Test.<anonymous> (test/test.js:94:34)
      at Test.assert (node_modules/supertest/lib/test.js:179:6)
      at assert (node_modules/supertest/lib/test.js:131:12)
      at node_modules/supertest/lib/test.js:128:5
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:706:12)
      at parser (node_modules/superagent/lib/node/index.js:906:18)
      at IncomingMessage.res.on.e (node_modules/superagent/lib/node/parsers/json.js:19:7)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)

It is happening because we are calling a email API in the unit tests. We need to find another way to test this.

### Update [Required]
- [ ] Correct the unit test

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1-2 hours

**Comment by Buddhiprabha** [comment]
@paavininanda are you working on this?

**Comment by shreyans29** [comment]
@paavininanda  I would suggest renaming it to "Using Mocks for Unit Tests with external Dependencies". It would be more generalized and will be true for every other sevice.

**Comment by Buddhiprabha** [comment]
Is anyone working on this? If not @lunayach can look at this. Please confirm @paavininanda @shreyans29

**Comment by paavininanda** [comment]
No I am not working on this. @lunayach you can go ahead :)
